from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()


class Transaction(db.Model):
    __tablename__ = 'transactions'
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, nullable=False)
    ticker = db.Column(db.String(20), nullable=False)
    account = db.Column(db.String(50), nullable=False)
    type = db.Column(db.String(20), nullable=False)  # Buy, Sell, Dividend
    qty = db.Column(db.Float, nullable=False, default=0)
    price = db.Column(db.Float, nullable=False, default=0)
    currency = db.Column(db.String(5), nullable=False, default='CAD')
    amount_native = db.Column(db.Float, default=0)
    amount_cad = db.Column(db.Float, default=0)
    fees_cad = db.Column(db.Float, default=0)
    net_cad = db.Column(db.Float, default=0)
    notes = db.Column(db.String(300), default='')
    subtype = db.Column(db.String(50), default='')   # e.g. Contribution, RDSP Grant, RDSP Bond
    import_batch = db.Column(db.String(40))          # stamps rows from one import (for "recent" + undo)
    recurring_id = db.Column(db.Integer)             # set on rows generated by a RecurringRule
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class PriceCache(db.Model):
    __tablename__ = 'price_cache'
    ticker = db.Column(db.String(20), primary_key=True)
    price = db.Column(db.Float)
    prev_close = db.Column(db.Float)
    currency = db.Column(db.String(5))
    last_updated = db.Column(db.DateTime)
    meta_json = db.Column(db.Text)  # cached classification: asset type, sector, market cap, ETF look-through


class Account(db.Model):
    __tablename__ = 'accounts'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    type = db.Column(db.String(20))
    cash_balance = db.Column(db.Float, default=0)
    horizon = db.Column(db.String(20))  # time-horizon bucket override; None = derive from type
    managed = db.Column(db.Boolean, default=False)  # True = advisor/fund-managed (not self-traded)


class Setting(db.Model):
    __tablename__ = 'settings'
    key = db.Column(db.String(50), primary_key=True)
    value = db.Column(db.String(500))


class GIC(db.Model):
    __tablename__ = 'gics'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    institution = db.Column(db.String(100))
    account = db.Column(db.String(50))
    principal = db.Column(db.Float, default=0)
    rate = db.Column(db.Float, default=0)
    start_date = db.Column(db.Date)
    maturity_date = db.Column(db.Date)
    compounding = db.Column(db.String(20), default='Annual')


class WatchlistItem(db.Model):
    __tablename__ = 'watchlist'
    id = db.Column(db.Integer, primary_key=True)
    ticker = db.Column(db.String(20))
    company = db.Column(db.String(100))
    sector = db.Column(db.String(50))
    currency = db.Column(db.String(5), default='CAD')
    target_price = db.Column(db.Float)
    target_type = db.Column(db.String(10), default='below')  # 'below' = buy target, 'above' = price objective
    added_price = db.Column(db.Float)
    added_date = db.Column(db.Date)
    notes = db.Column(db.String(300))


class PortfolioSnapshot(db.Model):
    __tablename__ = 'portfolio_snapshots'
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, nullable=False, unique=True)
    total_book = db.Column(db.Float, default=0)
    total_market = db.Column(db.Float, default=0)
    total_cash = db.Column(db.Float, default=0)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class TickerMap(db.Model):
    __tablename__ = 'ticker_map'
    description = db.Column(db.String(100), primary_key=True)  # cleaned broker description
    ticker = db.Column(db.String(20), nullable=False)           # real yfinance ticker symbol


class RDSPPlanYear(db.Model):
    """One future year of the RDSP plan: the user's intended contribution and the
    grant/bond it earns. Past/current years (≤ the current year) are NOT stored —
    the RDSP tab derives those live from real transactions. Amounts are dollars
    (the rdsp.py engine works in cents and converts at the boundary). A null
    grant/bond means "let the rules engine compute it" rather than an override."""
    __tablename__ = 'rdsp_plan_years'
    year = db.Column(db.Integer, primary_key=True)
    contribution = db.Column(db.Float, default=0)
    grant = db.Column(db.Float)   # None → compute from CDSG rules
    bond = db.Column(db.Float)    # None → compute from CDSB rules
    locked = db.Column(db.Boolean, default=False)  # reserved: pin a row against re-seeding


class RecurringRule(db.Model):
    """A transaction template that repeats on a schedule. The engine in
    recurring.py materializes concrete Transaction rows from these up to today."""
    __tablename__ = 'recurring_rules'
    id = db.Column(db.Integer, primary_key=True)
    # transaction template (mirrors the Add-Transaction form fields)
    account = db.Column(db.String(50), nullable=False)
    ticker = db.Column(db.String(20), default='CASH')
    type = db.Column(db.String(20), nullable=False)
    qty = db.Column(db.Float, default=0)
    price = db.Column(db.Float, default=0)
    currency = db.Column(db.String(5), default='CAD')
    amount = db.Column(db.Float, default=0)          # for income/cash types (single total)
    fees = db.Column(db.Float, default=0)
    notes = db.Column(db.String(300), default='')
    subtype = db.Column(db.String(50), default='')
    # schedule
    frequency = db.Column(db.String(12), nullable=False)  # weekly/monthly/quarterly/yearly
    next_date = db.Column(db.Date, nullable=False)        # next occurrence to generate
    end_date = db.Column(db.Date)                         # optional stop date
    count_remaining = db.Column(db.Integer)              # optional remaining occurrences
    active = db.Column(db.Boolean, default=True)
    last_run = db.Column(db.Date)
    # Buy/Reinvest by a fixed $ amount (mutual-fund PAC): qty is derived from the
    # NAV on each occurrence date rather than being fixed.
    dollar_based = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    @property
    def short(self):
        """Account-less description of the rule (for grouped lists)."""
        if self.dollar_based and self.type in ('Buy', 'Reinvest'):
            return f"{self.type} ${self.amount:,.2f} of {self.ticker}"
        if self.type in ('Buy', 'Sell', 'Reinvest'):
            return f"{self.type} {self.qty:g} {self.ticker} @ ${self.price:,.2f}"
        if self.type == 'Split':
            return f"Split {self.ticker} +{self.qty:g}"
        tail = '' if (self.ticker or 'CASH') == 'CASH' else f" · {self.ticker}"
        return f"{self.type} ${self.amount:,.2f} {self.currency}{tail}"

    @property
    def summary(self):
        """Short human description for the recurring-rules list."""
        return f"{(self.frequency or '').capitalize()}: {self.short} → {self.account}"
